import type { Instructor } from "../types";

export const TRAINING_CATEGORIES = [
  { id: "new", label: "מתחמש חדש", icon: "new", color: "#4ade80" },
  { id: "refresh", label: "רענון אקדח", icon: "refresh", color: "#60a5fa" },
  { id: "renewal", label: "חידוש רישיון", icon: "renewal", color: "#fbbf24" },
  { id: "group", label: "אימוני קבוצות", icon: "group", color: "#a78bfa" },
  { id: "pro", label: "ירי מקצועי", icon: "pro", color: "#f87171", hasLevels: true },
];

export const SKILL_LEVELS = [
  { min: 1000, max: 1200, label: "מתחיל" },
  { min: 1200, max: 1400, label: "בסיסי" },
  { min: 1400, max: 1600, label: "בינוני" },
  { min: 1600, max: 1800, label: "מתקדם" },
  { min: 1800, max: 9999, label: "מקצוען" },
];

export const MOCK_INSTRUCTORS: Instructor[] = [
  {
    id: "1", name: "דוד כהן",
    photo: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop&crop=face",
    verified: true, eloShooting: 1847, eloInstruction: 1780, stars: 4.9,
    metrics: { service: 4.9, professionalism: 5.0, quality: 4.8 },
    trainees: 1243, trainingTypes: ["מתחמש חדש", "רענון", "חידוש", "ירי מקצועי"],
    ranges: ["מטווח השרון", "מטווח נתניה"], city: "נתניה",
    available: true, nextSlot: "היום, 14:00", priceFrom: 250,
    bio: "מדריך ירי מוסמך עם 15 שנות ניסיון. שירתתי כקצין נשק ביחידה מיוחדת. מתמחה בהכשרת מתחמשים חדשים ואימוני ירי מתקדמים.",
    experience: 15,
    reviews: [
      { id: "r1", name: "יוסי לוי", date: "לפני שבוע", text: "מדריך מעולה! סבלני ומקצועי. הרגשתי בטוח לאורך כל האימון.", rating: 5, verified: true },
      { id: "r2", name: "שרה כהן", date: "לפני חודש", text: "האימון הכי טוב שהיה לי. דוד יודע להסביר בצורה ברורה ופשוטה.", rating: 5, verified: true },
      { id: "r3", name: "משה דוד", date: "לפני חודשיים", text: "מקצוען אמיתי. שיפרתי את הדיוק שלי משמעותית.", rating: 4, verified: true },
    ],
    gallery: [
      "https://images.unsplash.com/photo-1595590424283-b8f17842773f?w=600&h=400&fit=crop",
      "https://images.unsplash.com/photo-1584281722234-404e4dc10ae2?w=600&h=400&fit=crop",
    ],
    videos: [
      { id: "v1", title: "אימון ירי מעשי - טכניקת שליפה", thumbnail: "https://images.unsplash.com/photo-1595590424283-b8f17842773f?w=400&h=225&fit=crop", platform: "youtube" },
      { id: "v2", title: "טיפים למתחמש חדש", thumbnail: "https://images.unsplash.com/photo-1584281722234-404e4dc10ae2?w=400&h=225&fit=crop", platform: "instagram" },
    ],
    socialLinks: { youtube: "https://youtube.com", instagram: "https://instagram.com" },
  },
  {
    id: "2", name: "מיכל אברהם",
    photo: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop&crop=face",
    verified: true, eloShooting: 1523, eloInstruction: 1720, stars: 4.8,
    metrics: { service: 5.0, professionalism: 4.8, quality: 4.7 },
    trainees: 856, trainingTypes: ["מתחמש חדש", "רענון", "אימוני קבוצות"],
    ranges: ["מטווח תל אביב", "מטווח ראשון לציון"], city: "תל אביב",
    available: true, nextSlot: "מחר, 09:00", priceFrom: 280,
    bio: "מדריכת ירי מוסמכת, לוחמת בעבר ביחידת אגוז. מאמינה בגישה אישית ובסביבה תומכת.",
    experience: 8,
    reviews: [
      { id: "r4", name: "רונית כץ", date: "לפני 3 ימים", text: "מיכל מעולה, במיוחד למי שמפחד מנשק. יצרה אווירה נעימה ובטוחה.", rating: 5, verified: true },
    ],
    gallery: ["https://images.unsplash.com/photo-1595590424283-b8f17842773f?w=600&h=400&fit=crop"],
    videos: [
      { id: "v-2a", title: "אימון ירי לנשים", thumbnail: "https://images.unsplash.com/photo-1584281722234-404e4dc10ae2?w=400&h=225&fit=crop", platform: "instagram" },
      { id: "v-2b", title: "הכנה לאימון ראשון", thumbnail: "https://images.unsplash.com/photo-1595590424283-b8f17842773f?w=400&h=225&fit=crop", platform: "youtube" },
    ],
    socialLinks: { instagram: "https://instagram.com", facebook: "https://facebook.com" },
  },
  {
    id: "3", name: "אלון ברק",
    photo: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&h=200&fit=crop&crop=face",
    verified: true, eloShooting: 1956, eloInstruction: 1850, stars: 5.0,
    metrics: { service: 4.8, professionalism: 5.0, quality: 5.0 },
    trainees: 2100, trainingTypes: ["ירי מקצועי", "חידוש", "רענון"],
    ranges: ["מטווח ירושלים", "מטווח מעלה אדומים", "מטווח בית שמש"], city: "ירושלים",
    available: false, nextSlot: "יום ראשון, 10:00", priceFrom: 350,
    bio: "קצין נשק ותיק (20+ שנה), מדריך ירי ספורטיבי ומעשי. מנהל את אקדמיית הירי 'ברק'.",
    experience: 22,
    reviews: [
      { id: "r6", name: "תומר שמש", date: "לפני שבוע", text: "פשוט הטוב ביותר. אלון לקח אותי מרמת מתחיל לרמת תחרותי.", rating: 5, verified: true },
    ],
    gallery: [],
    videos: [
      { id: "v3", title: "ירי תחרותי IPSC - שלב מתקדם", thumbnail: "https://images.unsplash.com/photo-1584281722234-404e4dc10ae2?w=400&h=225&fit=crop", platform: "youtube" },
    ],
    socialLinks: { youtube: "https://youtube.com", facebook: "https://facebook.com" },
  },
  {
    id: "4", name: "יעל שפירא",
    photo: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&h=200&fit=crop&crop=face",
    verified: false, eloShooting: 1134, eloInstruction: 1340, stars: 4.6,
    metrics: { service: 4.7, professionalism: 4.5, quality: 4.6 },
    trainees: 412, trainingTypes: ["מתחמש חדש", "רענון"],
    ranges: ["מטווח חיפה"], city: "חיפה",
    available: true, nextSlot: "היום, 16:30", priceFrom: 220,
    bio: "מדריכת ירי עם 5 שנות ניסיון. אוהבת לעבוד עם מתחילים וליצור חוויה חיובית ראשונה.",
    experience: 5,
    reviews: [
      { id: "r7", name: "נועה לב", date: "לפני חודש", text: "יעל נהדרת! הפכה את האימון הראשון שלי לחוויה מהנה.", rating: 5, verified: true },
    ],
    gallery: [],
    videos: [
      { id: "v-4a", title: "טיפים לאימון ראשון", thumbnail: "https://images.unsplash.com/photo-1595590424283-b8f17842773f?w=400&h=225&fit=crop", platform: "instagram" },
    ],
  },
  {
    id: "5", name: "רון מלכה",
    photo: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&h=200&fit=crop&crop=face",
    verified: true, eloShooting: 1689, eloInstruction: 1550, stars: 4.7,
    metrics: { service: 4.6, professionalism: 4.8, quality: 4.7 },
    trainees: 678, trainingTypes: ["רענון", "חידוש", "אימוני קבוצות", "ירי מקצועי"],
    ranges: ["מטווח באר שבע", "מטווח אילת"], city: "באר שבע",
    available: true, nextSlot: "מחר, 11:00", priceFrom: 200,
    bio: "מדריך ירי ותיק מהדרום. 12 שנות ניסיון בהדרכה במטווחים אזרחיים וצבאיים.",
    experience: 12,
    reviews: [
      { id: "r9", name: "עמית דר", date: "לפני שבוע", text: "מקצועי ויעיל. סיימנו בזמן ובלי בעיות.", rating: 4, verified: true },
    ],
    gallery: [],
    videos: [
      { id: "v-5a", title: "רענון ירי בבאר שבע", thumbnail: "https://images.unsplash.com/photo-1584281722234-404e4dc10ae2?w=400&h=225&fit=crop", platform: "youtube" },
    ],
    socialLinks: { facebook: "https://facebook.com" },
  },
  {
    id: "6", name: "נתן גולדשטיין",
    photo: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=200&h=200&fit=crop&crop=face",
    verified: true, eloShooting: 1802, eloInstruction: 1690, stars: 4.8,
    metrics: { service: 4.9, professionalism: 4.9, quality: 4.7 },
    trainees: 1567, trainingTypes: ["מתחמש חדש", "רענון", "חידוש", "אימוני קבוצות"],
    ranges: ["מטווח פתח תקווה", "מטווח כפר סבא", "מטווח הוד השרון"], city: "פתח תקווה",
    available: false, nextSlot: "יום שלישי, 08:00", priceFrom: 270,
    bio: "בעל ניסיון של 18 שנה בהדרכת ירי. מנהל בית ספר לירי במרכז.",
    experience: 18,
    reviews: [
      { id: "r10", name: "ליאור חן", date: "לפני שבועיים", text: "נתן מדריך ברמה הכי גבוהה. ממליץ!", rating: 5, verified: true },
    ],
    gallery: [],
    videos: [
      { id: "v4", title: "סיור במטווח פתח תקווה", thumbnail: "https://images.unsplash.com/photo-1595590424283-b8f17842773f?w=400&h=225&fit=crop", platform: "facebook" },
    ],
    socialLinks: { facebook: "https://facebook.com", youtube: "https://youtube.com" },
  },
  // --- New instructors ---
  {
    id: "7", name: "עומר חדד",
    photo: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=200&h=200&fit=crop&crop=face",
    verified: false, eloShooting: 720, eloInstruction: 810, stars: 4.0,
    metrics: { service: 4.2, professionalism: 3.9, quality: 4.0 },
    trainees: 87, trainingTypes: ["מתחמש חדש", "רענון"],
    ranges: ["מטווח אשדוד"], city: "אשדוד",
    available: true, nextSlot: "היום, 10:00", priceFrom: 150,
    bio: "מדריך ירי צעיר ונלהב. סיימתי קורס הדרכה לפני שנתיים. מתמקד בהנגשת עולם הירי למתחילים.",
    experience: 2,
    reviews: [
      { id: "r11", name: "דנה קטן", date: "לפני שבוע", text: "סבלני מאוד, הרגשתי בנוח.", rating: 4, verified: true },
    ],
    gallery: [],
    videos: [
      { id: "v-7a", title: "למה חשוב להתחמש?", thumbnail: "https://images.unsplash.com/photo-1595590424283-b8f17842773f?w=400&h=225&fit=crop", platform: "instagram" },
    ],
  },
  {
    id: "8", name: "שמעון פרץ",
    photo: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200&h=200&fit=crop&crop=face",
    verified: true, eloShooting: 1920, eloInstruction: 1420, stars: 4.5,
    metrics: { service: 4.2, professionalism: 4.9, quality: 4.5 },
    trainees: 340, trainingTypes: ["ירי מקצועי", "רענון"],
    ranges: ["מטווח הרצליה", "מטווח תל אביב"], city: "הרצליה",
    available: true, nextSlot: "מחר, 08:00", priceFrom: 380,
    bio: "יורה תחרותי עם 10 מדליות ארציות. מתמחה באימוני IPSC ו-IDPA. הדגש על ביצועים.",
    experience: 14,
    reviews: [
      { id: "r12", name: "גל עוז", date: "לפני שבוע", text: "רמה מטורפת של ירי, אבל קצת פחות סבלני עם מתחילים.", rating: 4, verified: true },
    ],
    gallery: [],
    videos: [
      { id: "v5", title: "תחרות IPSC - גמר ארצי", thumbnail: "https://images.unsplash.com/photo-1584281722234-404e4dc10ae2?w=400&h=225&fit=crop", platform: "youtube" },
    ],
    socialLinks: { youtube: "https://youtube.com", instagram: "https://instagram.com" },
  },
  {
    id: "9", name: "לימור דיין",
    photo: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&h=200&fit=crop&crop=face",
    verified: true, eloShooting: 1280, eloInstruction: 1650, stars: 4.9,
    metrics: { service: 5.0, professionalism: 4.8, quality: 4.9 },
    trainees: 1890, trainingTypes: ["מתחמש חדש", "רענון", "אימוני קבוצות", "חידוש"],
    ranges: ["מטווח רחובות", "מטווח ראשון לציון"], city: "רחובות",
    available: true, nextSlot: "היום, 12:00", priceFrom: 260,
    bio: "מדריכת ירי עם 10 שנות ניסיון. מומחית בהדרכת קבוצות ובבניית ביטחון אישי סביב נשק.",
    experience: 10,
    reviews: [
      { id: "r13", name: "מאיה גור", date: "לפני 4 ימים", text: "לימור פשוט מדהימה! ההדרכה הכי טובה שקיבלתי.", rating: 5, verified: true },
      { id: "r14", name: "אורי שגב", date: "לפני חודש", text: "באתי בלי ניסיון ויצאתי עם ביטחון. מדריכה ברמה אחרת.", rating: 5, verified: true },
    ],
    gallery: ["https://images.unsplash.com/photo-1595590424283-b8f17842773f?w=600&h=400&fit=crop"],
    videos: [
      { id: "v-9a", title: "אימון קבוצתי ברחובות", thumbnail: "https://images.unsplash.com/photo-1584281722234-404e4dc10ae2?w=400&h=225&fit=crop", platform: "youtube" },
      { id: "v-9b", title: "טיפים לנשים מתחמשות", thumbnail: "https://images.unsplash.com/photo-1595590424283-b8f17842773f?w=400&h=225&fit=crop", platform: "instagram" },
    ],
    socialLinks: { instagram: "https://instagram.com" },
  },
  {
    id: "10", name: "איתי מזרחי",
    photo: "https://images.unsplash.com/photo-1531427186611-ecfd6d936c79?w=200&h=200&fit=crop&crop=face",
    verified: false, eloShooting: 890, eloInstruction: 950, stars: 4.2,
    metrics: { service: 4.3, professionalism: 4.1, quality: 4.2 },
    trainees: 156, trainingTypes: ["מתחמש חדש", "רענון"],
    ranges: ["מטווח מודיעין"], city: "מודיעין",
    available: false, nextSlot: "יום רביעי, 15:00", priceFrom: 180,
    bio: "מדריך ירי מוסמך עם 3 שנות ניסיון. מגיע מרקע צבאי בשריון. גישה ישירה ויעילה.",
    experience: 3,
    reviews: [
      { id: "r15", name: "רותם לב", date: "לפני חודשיים", text: "אימון טוב ויעיל, מגיע לעניין.", rating: 4, verified: true },
    ],
    gallery: [],
    videos: [
      { id: "v-10a", title: "מה לצפות באימון ראשון", thumbnail: "https://images.unsplash.com/photo-1595590424283-b8f17842773f?w=400&h=225&fit=crop", platform: "youtube" },
    ],
  },
  {
    id: "11", name: "אבי טל",
    photo: "https://images.unsplash.com/photo-1463453091185-61582044d556?w=200&h=200&fit=crop&crop=face",
    verified: true, eloShooting: 1750, eloInstruction: 1580, stars: 4.7,
    metrics: { service: 4.7, professionalism: 4.8, quality: 4.6 },
    trainees: 920, trainingTypes: ["רענון", "חידוש", "ירי מקצועי"],
    ranges: ["מטווח עפולה", "מטווח נצרת"], city: "עפולה",
    available: true, nextSlot: "מחר, 14:00", priceFrom: 230,
    bio: "מדריך ירי עם 16 שנות ניסיון מהצפון. לוחם מג\"ב לשעבר. מתמחה ברענון ובחידוש.",
    experience: 16,
    reviews: [
      { id: "r16", name: "שלמה ימיני", date: "לפני שבוע", text: "מדריך מצוין, מקצועי ומסודר.", rating: 5, verified: true },
    ],
    gallery: [],
    videos: [
      { id: "v-11a", title: "ירי מדויק - טכניקות בסיסיות", thumbnail: "https://images.unsplash.com/photo-1584281722234-404e4dc10ae2?w=400&h=225&fit=crop", platform: "youtube" },
    ],
    socialLinks: { youtube: "https://youtube.com" },
  },
  {
    id: "12", name: "תמר רוזנפלד",
    photo: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=200&h=200&fit=crop&crop=face",
    verified: false, eloShooting: 610, eloInstruction: 720, stars: 3.8,
    metrics: { service: 4.0, professionalism: 3.7, quality: 3.8 },
    trainees: 45, trainingTypes: ["מתחמש חדש"],
    ranges: ["מטווח אשקלון"], city: "אשקלון",
    available: true, nextSlot: "היום, 17:00", priceFrom: 160,
    bio: "מדריכת ירי חדשה בתחום. סיימתי הסמכה לפני שנה. מתמקדת בליווי נשים שמתחמשות לראשונה.",
    experience: 1,
    reviews: [
      { id: "r17", name: "ענבל גולן", date: "לפני שבועיים", text: "הרגשתי מאוד בנוח כאישה, ממליצה!", rating: 4, verified: true },
    ],
    gallery: [],
    videos: [
      { id: "v-12a", title: "ליווי נשים מתחמשות", thumbnail: "https://images.unsplash.com/photo-1595590424283-b8f17842773f?w=400&h=225&fit=crop", platform: "instagram" },
    ],
  },
  {
    id: "13", name: "יגאל נחום",
    photo: "https://images.unsplash.com/photo-1552058544-f2b08422138a?w=200&h=200&fit=crop&crop=face",
    verified: true, eloShooting: 1480, eloInstruction: 1730, stars: 4.9,
    metrics: { service: 5.0, professionalism: 4.9, quality: 4.8 },
    trainees: 2350, trainingTypes: ["מתחמש חדש", "רענון", "חידוש", "אימוני קבוצות", "ירי מקצועי"],
    ranges: ["מטווח ראשון לציון", "מטווח רמלה", "מטווח לוד"], city: "ראשון לציון",
    available: true, nextSlot: "היום, 09:00", priceFrom: 290,
    bio: "מנהל מטווח ומדריך ירי ותיק. 20 שנות ניסיון. מציע את כל סוגי האימונים. ידוע בסבלנות ובגישה מקצועית.",
    experience: 20,
    reviews: [
      { id: "r18", name: "חיים בר", date: "לפני 5 ימים", text: "יגאל הוא המדריך הכי סבלני שפגשתי. שווה כל שקל.", rating: 5, verified: true },
      { id: "r19", name: "סיון דוד", date: "לפני חודש", text: "הבן שלי עשה איתו חידוש וחזר מרוצה מאוד.", rating: 5, verified: true },
    ],
    gallery: ["https://images.unsplash.com/photo-1584281722234-404e4dc10ae2?w=600&h=400&fit=crop"],
    videos: [
      { id: "v6", title: "יום פתוח במטווח ראשון לציון", thumbnail: "https://images.unsplash.com/photo-1595590424283-b8f17842773f?w=400&h=225&fit=crop", platform: "facebook" },
    ],
    socialLinks: { facebook: "https://facebook.com", instagram: "https://instagram.com", youtube: "https://youtube.com" },
  },
  {
    id: "14", name: "אור כספי",
    photo: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=200&h=200&fit=crop&crop=face",
    verified: false, eloShooting: 1050, eloInstruction: 1100, stars: 4.3,
    metrics: { service: 4.4, professionalism: 4.2, quality: 4.3 },
    trainees: 210, trainingTypes: ["מתחמש חדש", "רענון", "אימוני קבוצות"],
    ranges: ["מטווח כפר סבא", "מטווח רעננה"], city: "כפר סבא",
    available: true, nextSlot: "מחר, 16:00", priceFrom: 190,
    bio: "מדריך ירי צעיר עם 4 שנות ניסיון. מגיע מיחידת חי\"ר. אוהב לעבוד עם קבוצות.",
    experience: 4,
    reviews: [
      { id: "r20", name: "נדב אורן", date: "לפני שבוע", text: "אימון קבוצתי מעולה, חוויה כיפית.", rating: 4, verified: true },
    ],
    gallery: [],
    videos: [
      { id: "v-14a", title: "אימון קבוצתי בכפר סבא", thumbnail: "https://images.unsplash.com/photo-1584281722234-404e4dc10ae2?w=400&h=225&fit=crop", platform: "facebook" },
    ],
  },
  {
    id: "15", name: "רינת שרון",
    photo: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=200&h=200&fit=crop&crop=face",
    verified: true, eloShooting: 1600, eloInstruction: 1480, stars: 4.6,
    metrics: { service: 4.5, professionalism: 4.7, quality: 4.6 },
    trainees: 530, trainingTypes: ["רענון", "חידוש", "ירי מקצועי"],
    ranges: ["מטווח קריית שמונה", "מטווח צפת"], city: "קריית שמונה",
    available: false, nextSlot: "יום חמישי, 09:00", priceFrom: 240,
    bio: "מדריכת ירי מקצועית מהצפון הרחוק. 9 שנות ניסיון. מתמחה בירי מדויק ובהכנה לתחרויות.",
    experience: 9,
    reviews: [
      { id: "r21", name: "נועם שטרן", date: "לפני חודש", text: "רינת עזרה לי לשפר את הדיוק באופן משמעותי. מקצוענית.", rating: 5, verified: true },
    ],
    gallery: [],
    videos: [
      { id: "v-15a", title: "ירי למרחקים - טכניקת כיוון", thumbnail: "https://images.unsplash.com/photo-1595590424283-b8f17842773f?w=400&h=225&fit=crop", platform: "youtube" },
    ],
    socialLinks: { instagram: "https://instagram.com" },
  },
];

export const AVAILABLE_DATES = [
  { date: "2026-02-12", slots: ["09:00", "10:30", "14:00", "16:00"] },
  { date: "2026-02-13", slots: ["08:00", "11:00", "15:00"] },
  { date: "2026-02-14", slots: ["09:00", "12:00"] },
  { date: "2026-02-15", slots: ["10:00", "14:00", "16:30"] },
  { date: "2026-02-16", slots: ["08:00", "09:30", "11:00", "14:00", "16:00"] },
];
