export { LawyerNavbar } from "./components/LawyerNavbar";
export { LawyerHero } from "./components/HeroSection";
export { ScenariosSection } from "./components/ScenariosSection";
export { SolutionSection } from "./components/SolutionSection";
export { PriceSection } from "./components/PriceSection";
export { TimelineSection } from "./components/TimelineSection";
export { FAQSection } from "./components/FAQSection";
export { LawyerCTA } from "./components/CTASection";
export { ContactModal } from "./components/ContactModal";
